### ISSUE TITLE
Owntracks (Android) crashes with csv format on the friends view

### ISSUE THREAD

**Issue by rcmcronny** [owntracks/android#1058]
App Build number: 23024
Android 10.0.1 (OxygenOS OnePlus 5T) latest official release

I use a little wemos with gps hat and your pico homie sketch, works great. As i want to have full data, i switched from json to csv format and since then, the android owntracks app crashed, when i switch to the friends view. 
(Info: I changed to lat/long coordinates somewhat for privacy reasons)

The log shows:
```
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): Expected space separating root-level values
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt:  at [Source: (byte[])"20,61168AE9,v,50000956,11000432,6,32,0,117,80"; line: 1, column: 4]
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:682)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1693)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1433)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:868)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:762)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.support.Parser.fromJson(Parser.java:63)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt$1.messageArrived(MessageProcessorEndpointMqtt.java:171)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at java.lang.Thread.run(Thread.java:919)
```
I thought it was mentioned, that csv is supported, was that an old information or is this a bug in the parsing code ?

Thanks,
Ronny

**Comment by jpmens** [comment]
our apps do not support CSV format, hence the crash I assume (which of course should not have happened :)

**Comment by growse** [comment]
Yeah - I'm not sure there's any CSV support within the app. But it shouldn't crash!

**Comment by jpmens** [comment]
There's bound NOT to be CSV support. (Info: CSV support we created for the now obsolete Greenwich devices  and I used that for the "Pico" :-) https://jpmens.net/2016/04/16/a-tiny-esp8266-based-gps-tracker/ )

**Comment by growse** [comment]
Hmm, I'm having difficulty replicating this. If I send a CSV message to an owntracks device topic for a friend that exists in the contacts list (or even one that doesn't), I get an error in the logcat that it can't parse the message, but it doesn't crash.

Checking the code for 2.3.0 (current prod version), the  `JsonParseException` should be handled by just logging and ignoring (`JsonParseException` is a subclass of `IOException`):

https://github.com/owntracks/android/blob/Android-v.2.3.0/project/app/src/main/java/org/owntracks/android/services/MessageProcessorEndpointMqtt.java#L182

Can I check what version you're seeing this on?

**Comment by rcmcronny** [comment]
@growse  I am on latest google play version (2.3.0 (15.03.2021). 

But perhaps, i missinterpreted the error source. I searched the logs and after that part above there is a sig 9 with some json beforehand. 
I send some LORA devices from my home automation through http api (and then republish to mqtt). 

Perhaps, there is a bug, or simply a brain bug on my side, here are the parts. 
I can also send the log privately, if needed. As there are geo location infos, i would not like to make them permanently online available.
(I have change city, address and lat/lon to some anonymous values, hope thats ok.

`08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: payload: 20,61168AE9,v,50000956,11000432,6,32,0,117,80 
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): Expected space separating root-level values
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt:  at [Source: (byte[])"20,61168AE9,v,50000956,11000432,6,32,0,117,80"; line: 1, column: 4]
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:682)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1693)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1433)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:868)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:762)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.support.Parser.fromJson(Parser.java:63)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt$1.messageArrived(MessageProcessorEndpointMqtt.java:171)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
08-18 09:53:44.232 25149  3763 E MessageProcessorEndpointMqtt: 	at java.lang.Thread.run(Thread.java:919)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: payload: {"_http":true,"_repub":true,"_type":"location","acc":1.0,"addr":"Strasse Str. 00, 01234 City, Germany","alt":300.0,"batt":100.0,"bs":0.0,"cc":"DE","conn":"w","created_at":1628769659.0,"device":"lgt92","ghash":"u301g4p","lat":50.004064,"locality":"City","lon":11.002246,"t":"p","tid":"cr","topic":"owntracks/car/lgt92","tst":1628769659.0,"username":"car","vac":3.0,"vel":0.0} 
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.owntracks.android.model.BatteryStatus` from Floating-point value (token `JsonToken.VALUE_NUMBER_FLOAT`)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt:  at [Source: (byte[])"{"_http":true,"_repub":true,"_type":"location","acc":1.0,"addr":"Strasse Str. 00, 01234 City, Germany","alt":300.0,"batt":100.0,"bs":0.0,"cc":"DE","conn":"w","created_at":1628769659.0,"device":"lgt92","ghash":"u301g4p","lat":50.004064,"locality":"City","lon":11.002246,"t":"p","tid":"cr","topic":"owntracks/car/lgt92","tst":1628769659.0,"username":"car","vac":3.0,"vel":0.0}"; line: 1, column: 143] (through reference chain: org.owntracks.android.model.messages.MessageLocation["bs"])
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeOther(EnumDeserializer.java:339)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:201)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:225)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:137)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:107)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.support.Parser.fromJson(Parser.java:63)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt$1.messageArrived(MessageProcessorEndpointMqtt.java:171)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
08-18 09:53:44.234 25149  3763 E MessageProcessorEndpointMqtt: 	at java.lang.Thread.run(Thread.java:919)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: payload: {"_http":true,"_repub":true,"_type":"location","addr":"Strasse Weg 0, 01234 City, Germany, Germany","alt":0.0,"batt":100.0,"bs":0.0,"cc":"DE","conn":"w","created_at":1629266416.0,"device":"oyster","ghash":"u301g1v","lat":50.0030986,"locality":"City","lon":11.0098059,"t":"p","tid":"oy","topic":"owntracks/car/oyster","tst":1629266416.0,"username":"car","vac":3.0,"vel":0.0} 
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.owntracks.android.model.BatteryStatus` from Floating-point value (token `JsonToken.VALUE_NUMBER_FLOAT`)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt:  at [Source: (byte[])"{"_http":true,"_repub":true,"_type":"location","addr":"Strasse Weg 0, 01234 City, Germany, Germany","alt":0.0,"batt":100.0,"bs":0.0,"cc":"DE","conn":"w","created_at":1629266416.0,"device":"oyster","ghash":"u301g1v","lat":50.0030986,"locality":"City","lon":11.0098059,"t":"p","tid":"oy","topic":"owntracks/car/oyster","tst":1629266416.0,"username":"car","vac":3.0,"vel":0.0}"; line: 1, column: 128] (through reference chain: org.owntracks.android.model.messages.MessageLocation["bs"])
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeOther(EnumDeserializer.java:339)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:201)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:225)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:137)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:107)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.support.Parser.fromJson(Parser.java:63)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt$1.messageArrived(MessageProcessorEndpointMqtt.java:171)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:519)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:417)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:214)
08-18 09:53:44.235 25149  3763 E MessageProcessorEndpointMqtt: 	at java.lang.Thread.run(Thread.java:919)
08-18 09:53:44.242 25149 27524 W System  : A resource failed to call close. 
08-18 09:53:52.498 25149 25149 I Surface : opservice is null false
08-18 09:53:52.524 25149 25149 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
08-18 09:53:52.544 25149 27586 I Counters: exceeded sample count in FrameTime
08-18 09:53:52.547 25149 25149 I MapActivity: Requested foreground location updates. isSuccessful: true isCancelled: false
08-18 09:53:52.557 25149 27586 I Counters: exceeded sample count in FrameTime
08-18 09:53:52.574 25149 27586 I Counters: exceeded sample count in FrameTime
08-18 09:53:55.152 25149 25149 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@b3b0394
08-18 09:53:55.213 25149 25149 E AndroidRuntime: FATAL EXCEPTION: main
08-18 09:53:55.213 25149 25149 E AndroidRuntime: Process: org.owntracks.android, PID: 25149
08-18 09:53:55.213 25149 25149 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.owntracks.android.model.messages.MessageLocation.getGeocode()' on a null object reference
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at org.owntracks.android.model.FusedContact.getGeocodedLocation(FusedContact.java:106)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at org.owntracks.android.databinding.UiRowContactBindingImpl.executeBindings(UiRowContactBindingImpl.java:147)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at org.owntracks.android.ui.contacts.FusedContactViewHolder.bind(ContactsAdapter.kt:39)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at org.owntracks.android.ui.contacts.ContactsAdapter.onBindViewHolder(ContactsAdapter.kt:22)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at org.owntracks.android.ui.contacts.ContactsAdapter.onBindViewHolder(ContactsAdapter.kt:14)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.View.layout(View.java:22085)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2834)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1947)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8048)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:902)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1091)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
08-18 09:53:55.213 25149 25149 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-18 09:53:55.245 25149 25149 I Process : Sending signal. PID: 25149 SIG: 9`

**Comment by jpmens** [comment]
Keeping your data private is what we expect. :-)
Gladly send your logs to ***@***.***

**Comment by growse** [comment]
Aha! This smells similar to #984 - the app assumed that if it knew about a contact, then that contact has a valid location. Obviously, this isn't necessarily true. 

`NullPointerException: Attempt to invoke virtual method 'java.lang.String org.owntracks.android.model.messages.MessageLocation.getGeocode()' on a null object reference` is the key line, when displaying the contact, it tries to reverse geocode the location (for display). Sometimes, there is no location. Then it explodes.

It's hopefully fixed in the next version. I should really get that released.

**Comment by rcmcronny** [comment]
Seems legit, i already did use the cards since some short time and tried the friends feature in the app a long time not. So this was not obvious to me. Many thanks for pointing me to this and sorry for duplicate report on this.
Keep up the good work.
