### ISSUE TITLE
ServiceBeacon IllegalArgumentException

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#106]
Receiver not registered: org.owntracks.android.support.BluetoothStateChangeReceiver@8e1e546

```
Caused by: java.lang.IllegalArgumentExceptionReceiver not registered: org.owntracks.android.support.BluetoothStateChangeReceiver@8e1e546
at org.owntracks.android.services.ServiceBeacon.onDestroy(ServiceBeacon.java:337)
at org.owntracks.android.services.ServiceProxy.onDestroy(ServiceProxy.java:53)
```

**Comment by binarybucks** [comment]
Included in 0.5.06
