### ISSUE TITLE
ActivityWaypoint NumberFormatException 

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#107]
```ActivityWaypoint.java:207
java.lang.NumberFormatExceptionInvalid float: "-
at org.owntracks.android.ActivityWaypoint.conditionallyEnableSaveButton(ActivityWaypoint.java:207)
at org.owntracks.android.ActivityWaypoint.access$000(ActivityWaypoint.java:37)
at org.owntracks.android.ActivityWaypoint$2.afterTextChanged(ActivityWaypoint.java:88)
```

**Comment by binarybucks** [comment]
Included in 0.5.06
