### ISSUE TITLE
Error mqtt conection

### ISSUE THREAD

**Issue by konstantin-teplitzky** [owntracks/android#1084]
* **24037**: 
* **11**:    
* **Xiaomi mi 11 ultra 12/512**: 

Mqtt error connection.
Log  
```
`2021-09-06 17:45:50.050 D MessageProcessor: processing location message owntracks/8host/richard. ThreadID: Thread[MQTT Call: 8hostkris,5,main]
2021-09-06 17:45:50.050 D FusedContact: Geocode location updated for owntracks/8host/richard: 56.xxx, 92.xxx
2021-09-06 17:45:50.050 E MQTT: connectionLost error
Соединение потеряно (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:270)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more

2021-09-06 17:45:50.050 D MQTT: Cancelling task tag PERIODIC_TASK_MQTT_KEEPALIVE threadID: Thread[MQTT Rec: 8hostkris,5,main]
2021-09-06 17:45:50.050 D MessageProcessor: message:MQTT Error: Соединение потеряно, 
2021-09-06 17:45:50.050 D BackgroundService: endpoint state changed Отключен. Message: MQTT Error: Соединение потеряно
Соединение потеряно (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:270)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
	... 1 more

2021-09-06 17:45:50.050 D MQTT: WorkManager queue task PERIODIC_TASK_MQTT_RECONNECT as 61ec0528-376c-48ed-b363-70824a9759bc
2021-09-06 17:45:50.050 I MQTTReconnectWorker: MQTTReconnectWorker Doing work on threadID: Thread[pool-3-thread-2,5,main]
2021-09-06 17:45:50.050 D MessageProcessorEndpointMqtt: Connecting to broker. ThreadId: Thread[networkHandlerThread,5,main]
2021-09-06 17:45:50.050 D MessageProcessorEndpointMqtt: Connecting on non-ui worker thread: Thread[networkHandlerThread,5,main]
2021-09-06 17:45:50.050 D MessageProcessor: message:null, 
2021-09-06 17:45:50.050 D BackgroundService: endpoint state changed Подключение. Message: null
2021-09-06 17:45:50.050 D MessageProcessorEndpointMqtt: Initializing new mqttClient
2021-09-06 17:45:50.050 D MessageProcessorEndpointMqtt: client id :8hostkris, connect string: ssl://mqtt.teplitzky.ru:8883
2021-09-06 17:45:52.052 D MessageProcessorEndpointMqtt: MQTT Connected success.
2021-09-06 17:45:52.052 D MQTT: WorkManager queue task PERIODIC_TASK_MQTT_KEEPALIVE as da7be6d7-6980-43c3-8526-c14e48e75b5e with interval 900
2021-09-06 17:45:52.052 D MessageProcessorEndpointMqtt: Connect Complete. Reconnected: false, serverUri:ssl://mqtt.teplitzky.ru:8883
2021-09-06 17:45:52.052 D MessageProcessor: message:null, 
2021-09-06 17:45:52.052 D MQTT: MQTT connected!. Running onconnect handler (threadID Thread[MQTT Call: 8hostkris,5,main])`
```

**Comment by growse** [comment]
(I redacted your lat/long - hope you don't mind).

Hmm, `connectionLost` is normally a network issue, but there may be other causes. I think that multiple clients connecting to the same broker with the same username / clientId causes a connection lost.

Does this issue happen regardless of what network you're on, and did this only start happening on 2.4? If you're able to downgrade to the 2.3 release (you can grab the apk from the releases page) and test, that'd be helpful.

**Comment by konstantin-teplitzky** [comment]
> (I redacted your lat/long - hope you don't mind).
thank you!
wrote by mobile... ;-)
> 
> Hmm, `connectionLost` is normally a network issue, but there may be other causes. I think that multiple clients connecting to the same broker with the same username / clientId causes a connection lost.
> 
> Does this issue happen regardless of what network you're on, and did this only start happening on 2.4? If you're able to downgrade to the 2.3 release (you can grab the apk from the releases page) and test, that'd be helpful.
i was try it - error is gone
try to watch for it in future - thanks!

**Comment by growse** [comment]
No problem. Please reopen if necessary.
