### ISSUE TITLE
SSL error when trying to connect to my private host

### ISSUE THREAD

**Issue by Peym77** [owntracks/android#1202]
I've setup a mqtt broker on my private domain and server. I've followed the instruction for setting up a self-signed certificate and importing it to my android, but I keep getting an error every time that I try to connect. 
I am certain that the mqtt broker is configured properly and works correctly with my ca.crt file because I am able to subscribe and publish messages using these commands from my personal laptop:
(Please note that I've replaced my actual domain with the word "host" because I didn't want to publicly put it here)

mosquitto_sub -h host -t test/subject -p 8883 --cafile ca.crt -u username -P password
mosquitto_pub -h host -t test/subject -p 8883 --cafile ca.crt -m ITWORKS -u username -P password

when I provide the correct cert file, username and password I am able to communicate with my broker from the terminal, but that does no work on the android app as I keep getting the following error. I've also selected ca.crt file as my CA certificate in the app. I don't know what am I doing wrong.

* **App build number**: version 2.4.7 (24704)
* **Android version**: 11 RKQ1.200826.002
* **Device**: Xiaomi
* **Installation source**: Google Play

```
2022-04-30 11:10:14.014 E MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker
org.owntracks.android.services.MqttConnectionException: MqttException (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: host, Peer Host: host
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(Unknown Source:22)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(Unknown Source:45)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.$r8$lambda$3UR4gQL2b_UbF_ekJLIMhafolpU(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt$$ExternalSyntheticLambda0.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: MqttException (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: host, Peer Host: host
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:55)
	at java.lang.Thread.run(Thread.java:923)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host: host Peer Host: host
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(Unknown Source:151)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(Unknown Source:15)
	... 1 more
```

**Comment by growse** [comment]
My best guess at the moment is that there is no SAN on the certificate that matches your server hostname.

Does the output of `openssl x509 -noout -ext subjectAltName  -in server-crt.pem` (where server-crt.pem is your server certificate) list a SAN that matches the hostname you're connecting to?

(Minor point: if you've got a CA.crt, your certificate is not self-signed.)

**Comment by Peym77** [comment]
This is what I get when running the command on my server
`openssl x509 -noout -ext subjectAltName -in server.crt 
No extensions in certificate
`
I'm guessing that means there is something wrong there? I didn't find any tutorials on how to properly setup mqtts in a way it would work properly with owntracks android app so I used this tutorial to set it up http://www.steves-internet-guide.com/mosquitto-tls/ (not expecting you to read the whole thing, but I put it here just in case)

got any tips on how can I fix this issue? on the owntracks website there's a link to a repository that is supposed to set these things up automatically, but I realised it's deprecated after I tried to run it so I'm a little bit lost atm.

**Comment by growse** [comment]
Ah, so this means that you've generated a certificate with no SANs. This was the correct approach about 7 years ago, but SAN-less server TLS certs have been deprecated for a while now.

Alas, the `openssl` tooling doesn't make life easy - it can be done, but you need to define a config file for `openssl` to use when generating the certificate. This is a google hit that seems to explain it pretty well: https://www.golinuxcloud.com/openssl-generate-csr-create-san-certificate/#Openssl_Generate_CSR_with_SAN_command_line

Personally, I use `mkcert` (https://mkcert.dev/) for generating CA/certs, mostly because it's much easier to use and also because Filippo knows what he's doing.

**Comment by Peym77** [comment]
Finally got it to work by making a config file using the tutorial you shared.
Thanks for the help!
