### ISSUE TITLE
ServiceBeacon.java line 267

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/android#126]
#### in org.owntracks.android.services.ServiceBeacon.refreshCustomParser

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550942235141dcfd8f281c7c](https://fabric.io/owntracks/android/apps/org.owntracks.android/issues/550942235141dcfd8f281c7c)

```
java.lang.UnsupportedOperationException
       at java.util.Collections$UnmodifiableCollection.remove(Collections.java:970)
       at org.owntracks.android.services.ServiceBeacon.refreshCustomParser(ServiceBeacon.java:267)
       at org.owntracks.android.services.ServiceBeacon.handlePreferences(ServiceBeacon.java:199)
       at org.owntracks.android.services.ServiceBeacon.access$000(ServiceBeacon.java:40)
       at org.owntracks.android.services.ServiceBeacon$1.onSharedPreferenceChanged(ServiceBeacon.java:164)
       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:476)
       at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:384)
       at android.preference.Preference.tryCommit(Preference.java:1403)
       at android.preference.Preference.persistString(Preference.java:1436)
       at org.owntracks.android.support.EditTextPreference.setText(EditTextPreference.java:49)
       at org.owntracks.android.support.EditTextPreference$1.onPositive(EditTextPreference.java:129)
       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:864)
       at android.view.View.performClick(View.java:4780)
       at android.view.View$PerformClick.run(View.java:19866)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by binarybucks** [comment]
@GeorgeHahn also, looking at the AltBeacon library code, your code never calls the library bind methods (hence the error that I mentioned in #70).
