### ISSUE TITLE
MessageProcessorEndpointHttp: HTTP Delivery failed 

### ISSUE THREAD

**Issue by eppesuig** [owntracks/android#1587]
* **App build number**: 2.4.12
* **Android version**: 12 (AC2003_11_F22)
* **Device**: OnePlus Nord
* **Installation source**: google play

I just installed the app and configured a server using websockets on a debian 12 system.
Now, the server logs is filled with these messages:

```
1706477444: New connection from 192.168.222.54:33374 on port 8883.
1706477444: Client <unknown> disconnected due to protocol error.
gen 28 22:30:44 mantide mosquitto[2516410]: 1706477444: New connection from 192.168.222.54:33374 on port 8883.
gen 28 22:30:44 mantide mosquitto[2516410]: 1706477444: Client <unknown> disconnected due to protocol error.
1706477452: New connection from 192.168.222.54:60942 on port 8883.
1706477452: Client <unknown> disconnected due to protocol error.
gen 28 22:30:52 mantide mosquitto[2516410]: 1706477452: New connection from 192.168.222.54:60942 on port 8883.
gen 28 22:30:52 mantide mosquitto[2516410]: 1706477452: Client <unknown> disconnected due to protocol error.
[...]
```

and the android app log contains these lines:

```
2024-01-28 22:19:36.116 E MessageProcessorEndpointHttp: HTTP Delivery failed 
java.io.IOException: unexpected end of stream on https://www.mydomain.tld:8883/...
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(SourceFile:118)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(SourceFile:5)
	at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:231)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:100)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:140)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:172)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:148)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:97)
	at okhttp3.internal.connection.RealCall.execute(SourceFile:42)
	at org.owntracks.android.services.MessageProcessorEndpointHttp.sendMessage(SourceFile:305)
	at org.owntracks.android.services.MessageProcessor.lambda$sendAvailableMessages$0(Unknown Source:2)
	at org.owntracks.android.services.MessageProcessor.$r8$lambda$bVYaIhYhXtJCzBaSxWOGtcUu6f8(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessor$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(SourceFile:165)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(SourceFile:19)
	... 23 more

2024-01-28 22:19:36.120 E MessageProcessor: Message delivery failed. queueLength: 8, messageId: 1706463030053-db6ac4
2024-01-28 22:19:36.121 W MessageProcessor: Error sending message. Re-queueing
2024-01-28 22:19:36.127 I MessageProcessor: Waiting for 120 s before retrying
```

I tried to get more information on the logs adding `log_type all` but nothing more was logged.

Do you already know how to solve this problem? May I provide more data?

Thanks

**Comment by growse** [comment]
You appear to be trying to connect to a mosquito server in HTTP mode?

**Comment by eppesuig** [comment]
Yes, you are right. I now corrected the connector to MQTT on the client and configured it for using websocket.
But I am still not able to connect to the server. The new exception is:

```
2024-01-29 10:36:14.670 I MQTTReconnectWorker: MQTTReconnectWorker started on threadID: Thread[androidx.work-3,5,main]
2024-01-29 10:36:14.838 E MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker
org.owntracks.android.services.MqttConnectionException:  (0) - java.io.IOException: WebSocket Response header: Invalid response from Server, It may not support WebSockets.
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(SourceFile:243)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(SourceFile:46)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.$r8$lambda$3UR4gQL2b_UbF_ekJLIMhafolpU(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt$$ExternalSyntheticLambda0.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by:  (0) - java.io.IOException: WebSocket Response header: Invalid response from Server, It may not support WebSockets.
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:433)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: WebSocket Response header: Invalid response from Server, It may not support WebSockets.
	at androidx.core.provider.FontRequest.execute(SourceFile:544)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(SourceFile:26)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:174)
	... 1 more
```

so, I double checked my server configuration and it is configured for websocket, but maybe it is running on a different port. The mosquitto log contents are:

```
1706521211: mosquitto version 2.0.11 starting
1706521211: Config loaded from /etc/mosquitto/mosquitto.conf.
1706521211: Opening ipv4 listen socket on port 8883.
1706521211: Opening websockets listen socket on port 1883.
1706521211: mosquitto version 2.0.11 running
```

in my configuration I heve these lines:
```
protocol websockets
listener 8883 192.168.222.54
```

interesting enough is that if I switch these lines, mosquitto does not start anymore. It gives error message:
```
1706521555: mosquitto version 2.0.11 starting
1706521555: Config loaded from /etc/mosquitto/mosquitto.conf.
1706521555: Opening websockets listen socket on port 8883.
1706521555: Error: Unable to start any listening sockets, exiting.
```

So, do the configuration lines require to be put in a specifi order in order to let MQTT use websocket on port 8883?

Thank you very much

**Comment by eppesuig** [comment]
I just found the solution: the first listener seems to always be related to the mqtt protocol. My working configureation specifies two listeners this way:

```
listener 1883 192.168.222.54
protocol mqtt
listener 8883 192.168.222.54
protocol websockets
```

and now, it starts with these messages:
```
1706523693: mosquitto version 2.0.11 starting
1706523693: Config loaded from /etc/mosquitto/mosquitto.conf.
1706523693: Opening ipv4 listen socket on port 1883.
1706523693: Opening websockets listen socket on port 8883.
1706523693: mosquitto version 2.0.11 running
```

Thank you again for your help.

**Comment by jpmens** [comment]
The `protocol` line specifies the listener's protocol, and you define the order as you like.

**Comment by eppesuig** [comment]
Thank you. I am closing the issue.
