### ISSUE TITLE
Couldn't attach file when sharing log via gmail

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#1600]
* **App build number**: 2.5.0
* **Device**: Samsung S8

When submitting logs, I want to attach to an outgoing Gmail message. The app indicates "could not attach file", and an empty email with Subject "OwnTracks Log File" is sent.

**Comment by growse** [comment]
Hmm. Works for Google Drive etc. Wonder if this is a GMail thing.

**Comment by jpmens** [comment]
You are right, it works for Drive, but I found this in the log which was submitted to Drive:

```
2024-02-04 13:53:08.211 E [AsyncTask #14] ExportedLogContentProvider: Can't write logs to output
java.io.IOException: write failed: EPIPE (Broken pipe)
	at libcore.io.IoBridge.write(IoBridge.java:531)
	at java.io.FileOutputStream.write(FileOutputStream.java:381)
	at java.io.FileOutputStream.write(FileOutputStream.java:359)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider.openFile$lambda$2(Unknown Source:27)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider.$r8$lambda$0FCHc_1e4Qd4KLhynmTWJo6dC2M(SourceFile:1)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider$$ExternalSyntheticLambda0.writeDataToPipe(SourceFile:1)
	at android.content.ContentProvider$1.doInBackground(ContentProvider.java:1863)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:288)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:348)
	at libcore.io.IoBridge.write(IoBridge.java:526)
	... 11 more

2024-02-04 13:53:08.366 E [AsyncTask #15] ExportedLogContentProvider: Can't write logs to output
java.io.IOException: write failed: EPIPE (Broken pipe)
	at libcore.io.IoBridge.write(IoBridge.java:531)
	at java.io.FileOutputStream.write(FileOutputStream.java:381)
	at java.io.FileOutputStream.write(FileOutputStream.java:359)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider.openFile$lambda$2(Unknown Source:27)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider.$r8$lambda$0FCHc_1e4Qd4KLhynmTWJo6dC2M(SourceFile:1)
	at org.owntracks.android.ui.status.logs.ExportedLogContentProvider$$ExternalSyntheticLambda0.writeDataToPipe(SourceFile:1)
	at android.content.ContentProvider$1.doInBackground(ContentProvider.java:1863)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:288)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:348)
	at libcore.io.IoBridge.write(IoBridge.java:526)
	... 11 more
```

Doesn't look right to me.

**Comment by growse** [comment]
I've a fix that should fix both gmail and drive.
