### ISSUE TITLE
Failing to connect to MQTT server with TLS (but Recorder succeeds) [Trust anchor for certification path not found]

### ISSUE THREAD

**Issue by VohGit** [owntracks/android#1720]
I run a Mosquitto MQTT docker container on a NAS, with the following settings:

```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
log_type all
per_listener_settings false

allow_anonymous false
require_certificate false
password_file /mosquitto/config/*redacted*

listener *redacted*
cafile /mosquitto/config/my-new-ca.crt
certfile /mosquitto/config/server.crt
keyfile /mosquitto/config/server.key
```

I also run the Owntracks Recorder docker container on the same NAS.

The Recorder is able to connect perfectly fine (with the "my-new-ca.crt") to the MQTT server, as can be seen in the mosquitto.log.

However, OwnTracks app, is not able to do so, with the same "my-new-ca.crt". I enabled TLS in the OwnTracks app, and added the crt-file. I also added it on the phone (Security > Encryption & credentials > Install a certificate > CA certificate.)

![bild](https://github.com/owntracks/android/assets/149908565/275a7cfa-4c8d-49e4-aa7c-4c94c41c0e91)

![bild](https://github.com/owntracks/android/assets/149908565/9c75f6ce-a7ea-4c60-b65c-b77de03ccc22)

![bild](https://github.com/owntracks/android/assets/149908565/be897f2e-cd50-4c54-a236-1fe8a754ab83)

Here's the error from mosquitto.log:

> OpenSSL Error[0]: error:1403F416:SSL routines:ACCEPT_SR_FINISHED:sslv3 alert certificate unknown
> Client <unknown> disconnected: Protocol error.

Here's the errors from OwnTracks app:

```
E MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker
org.owntracks.android.services.MqttConnectionException:  (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(SourceFile:243)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(SourceFile:46)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.$r8$lambda$3UR4gQL2b_UbF_ekJLIMhafolpU(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt$$ExternalSyntheticLambda0.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
Caused by:  (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:433)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.conscrypt.SSLUtils.toSSLHandshakeException(Unknown Source:13)
	at org.conscrypt.ConscryptEngine.convertException(Unknown Source:14)
	at org.conscrypt.ConscryptEngine.readPlaintextData(Unknown Source:38)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:253)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:28)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:11)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(SourceFile:70)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(Unknown Source:0)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(Unknown Source:90)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(Unknown Source:36)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(Unknown Source:83)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:174)
	... 1 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.conscrypt.TrustManagerImpl.verifyChain(SourceFile:191)
	at org.conscrypt.TrustManagerImpl.checkTrustedRecursive(Unknown Source:73)
	at org.conscrypt.TrustManagerImpl.checkTrusted(Unknown Source:64)
	at org.conscrypt.TrustManagerImpl.checkTrusted(Unknown Source:61)
	at org.conscrypt.TrustManagerImpl.getTrustedChainForServer(Unknown Source:24)
	at org.conscrypt.TrustManagerImpl.checkServerTrusted(Unknown Source:0)
	at org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(Unknown Source:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.conscrypt.Platform.checkTrusted(Unknown Source:32)
	at org.conscrypt.Platform.checkServerTrusted(Unknown Source:8)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(Unknown Source:36)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(Unknown Source:16)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(Unknown Source:6)
	at org.conscrypt.ConscryptEngine.readPlaintextData(Unknown Source:21)
	... 10 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.conscrypt.TrustManagerImpl.verifyChain(SourceFile:188)
	... 24 more
```

I've been running this setup flawlessly for quite some months but had to renew/create new certificates. I've used the SAN extension so my certs are related to both the DNS name and IP-address of the NAS.
Can this be related to the *breaking changes* of the latest beta version? Although I'm still using v 2.4.12, so it shouldn't, right?
I also tried the beta version though, but without success.

App build number: 2.4.12
Android version: 14
Device: Google Pixel 6a. **NOTE:** GrapheneOS installed.
Installation source: Manually from the APK (owntracks-release-oss-v2.4.12.apk)

**Comment by jpmens** [comment]
In the first error reported by the app I see `Trust anchor for certification path not found`. This indicates to me that the cert cannot be found. 

I assume it's a path problem, but as you've added the cert to the OS I think you can omit it from our app.

**Comment by VohGit** [comment]
I found some interesting lines by holding down the app icon, then pressing "About" --> "View logs".

> type: logcat
> osVersion: google/bluejay/bluejay:14/AP1A.240505.004/2024052100:user/release-keys
> packageName: org.owntracks.android:420412000
> buffers: main,system,crash,events,kernel
> level: verbose
> 
> [...]
> 
> D MessageProcessorEndpointMqtt: Initializing new mqttClient
> D MessageProcessorEndpointMqtt: client id :*redacted*, connect string: ssl://*redacted*
> V SocketFactory: initializing CustomSocketFactory
> V SocketFactory: options.hasCaCrt(): true
> V SocketFactory: Certificate Owner: CN=*redacted*, OU=*redacted*, O=*redacted*, L=*redacted*, ST=*redacted*, C=*redacted*
> V SocketFactory: Certificate Issuer: CN=*redacted*, OU=*redacted*, O=*redacted*, L=*redacted*, ST=*redacted*, C=*redacted*
> V SocketFactory: Certificate Serial Number: *redacted*
> V SocketFactory: Certificate Algorithm: SHA256withRSA
> V SocketFactory: Certificate Version: 3
> V SocketFactory: Certificate OID: 1.2.840.113549.1.1.11
> V SocketFactory: Alias: CN=*redacted*,OU=*redacted*,O=*redacted*,L=*redacted*,ST=*redacted*,C=*redacted* isKeyEntry:false isCertificateEntry:true
> V SocketFactory: Client .p12 sideload: false, using null client cert
> V MessageProcessorEndpointMqtt: MQTT connecting synchronously
> 05-24 21:55:35.826 17075 19358 D TrafficStats: tagSocket(103) with statsTag=0xffffffff, statsUid=-1
> 05-24 21:55:35.862 17075 17107 D MessageProcessorEndpointMqtt: Releasing connectinglock
> 05-24 21:55:35.865 17075 17107 D MessageProcessor: message:MQTT Error: , 
> 05-24 21:55:35.866 17075 17107 W MessageProcessorEndpointMqtt: failed connection attempts: 356

I interpret this as it does in fact find my certificate? (As I can see it mentioned in these lines, with correct values for CN, OU, and so on.

I did try to omit the certificate from the app and only have it the phone settings (Security > Encryption & credentials > Install a certificate > CA certificate), and I also tried vice versa, but with no success.

**Comment by VohGit** [comment]
Okay, problem solved.

I tried on another phone, just to rule out the phone/Graphene OS - didn't work either.

I then SSH:d into my NAS and ran the beautiful [generate-CA.sh](https://github.com/owntracks/tools/blob/master/TLS/generate-CA.sh), and used those certs. And voila, now it works.

I think the problem might have been bad/incorrect options for keyUsage and basicConstraints when I created my own certs, as my experience with this is limited. To anyone facing similar issues, just run the generate-CA.sh instead, from the server you're hosting your broker!

**Comment by jpmens** [comment]
Glad you got it working.

> To anyone facing similar issues, just run the generate-CA.sh instead, from the server you're hosting your broker!

I like to recommend not doing this but using one of the many ACME providers (e.g. Let's Encrypt); they provide certificates free of charge, and we don't need to do anything on the smartphones, as their cert stores alread contain the appropriate roots. True that Let's Encrypt certificates have to be renewed every 90 days, but that is not terribly hard to automate.
