### ISSUE TITLE
adding new region (clicking + button in top right) crashes app

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/android#327]
crash log sent

**Comment by binarybucks** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.owntracks.android/org.owntracks.android.activities.ActivityRegion}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2474)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5696)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at org.owntracks.android.activities.ActivityRegion.setupListenerAndRequiredFields(ActivityRegion.java:129)
	at org.owntracks.android.activities.ActivityRegion.onCreate(ActivityRegion.java:108)
	at android.app.Activity.performCreate(Activity.java:5958)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2364)
	... 10 more
```
