### ISSUE TITLE
062: crash on export prefs as soon as checkmark is tapped

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#331]

**Comment by jpmens** [comment]
Report sent

**Comment by binarybucks** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at org.owntracks.android.messages.MessageWaypoint.fromDaoObject(MessageWaypoint.java:119)
	at org.owntracks.android.support.Preferences.waypointsToJSON(Preferences.java:381)
	at org.owntracks.android.support.Preferences.exportToMessage(Preferences.java:985)
	at org.owntracks.android.activities.ActivityExport.export(ActivityExport.java:63)
	at org.owntracks.android.activities.ActivityExport.onOptionsItemSelected(ActivityExport.java:49)
	at android.app.Activity.onMenuItemSelected(Activity.java:2885)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:404)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:185)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
