### ISSUE TITLE
WakeLock under-locked org.owntracks.android.wakelock.broker.ping

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#353]
Needs investigation. 
Only occurred once so far. 
Unable to find an issue as the code correctly checks if the wakelock is held or not before trying to release it. 
```
java.lang.RuntimeException: Unable to start service org.owntracks.android.services.ServiceProxy@3b6ebef9 with Intent { act=org.owntracks.android.RECEIVER_ACTION_PING flg=0x14 cmp=org.owntracks.android/.services.ServiceProxy (has extras) }: java.lang.RuntimeException: WakeLock under-locked org.owntracks.android.wakelock.broker.ping
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2937)
	at android.app.ActivityThread.access$2100(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5321)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.RuntimeException: WakeLock under-locked org.owntracks.android.wakelock.broker.ping
	at android.os.PowerManager$WakeLock.release(PowerManager.java:998)
	at android.os.PowerManager$WakeLock.release(PowerManager.java:969)
	at org.owntracks.android.services.ServiceBroker$PingHandler.ping(ServiceBroker.java:920)
	at org.owntracks.android.services.ServiceBroker.onStartCommand(ServiceBroker.java:286)
	at org.owntracks.android.services.ServiceProxy.onStartCommand(ServiceProxy.java:87)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2920)
	... 9 more
```

**Comment by binarybucks** [comment]
Fixed
