### ISSUE TITLE
NullPointerException at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#366]
Steps to reproduce: 
* crash after trying open advance settings
* happens every time I try to go into the mode settings. chose public matt from install screen

```
java.lang.NullPointerException
	at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
	at android.support.v4.graphics.drawable.DrawableCompatBase.setTintList(DrawableCompatBase.java:42)
	at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTintList(DrawableCompat.java:94)
	at android.support.v4.graphics.drawable.DrawableCompat.setTintList(DrawableCompat.java:390)
	at com.afollestad.materialdialogs.internal.MDTintHelper.setTint(MDTintHelper.java:45)
	at com.afollestad.materialdialogs.DefaultAdapter.getView(DefaultAdapter.java:67)
	at android.widget.AbsListView.obtainView(AbsListView.java:2090)
	at android.widget.ListView.measureHeightOfChildren(ListView.java:1485)
	at android.widget.ListView.onMeasure(ListView.java:1348)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5045)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5045)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12937)
	at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5045)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5045)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5045)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2178)
	at android.view.View.measure(View.java:12937)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1227)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2700)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:5109)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:991)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by binarybucks** [comment]
See https://github.com/afollestad/material-dialogs/issues/1006
