### ISSUE TITLE
RejectedExecutionException for contact resolver task

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#414]
```
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@12fc09f5 rejected from java.util.concurrent.ThreadPoolExecutor@8d7138a[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 628]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:594)
    at org.owntracks.android.support.ContactImageProvider.setImageViewAsync(ContactImageProvider.java:93)
    at org.owntracks.android.model.FusedContact.displayFaceInViewAsync(FusedContact.java:112)
    at org.owntracks.android.databinding.UiRowContactBinding.executeBindings(UiRowContactBinding.java:176)
    at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:355)
    at org.owntracks.android.ui.base.BaseAdapter.onBindBinding(BaseAdapter.java:80)
    at org.owntracks.android.ui.base.BaseAdapter.onBindViewHolder(BaseAdapter.java:163)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5825)
    at org.owntracks.android.ui.base.BaseAdapter.onBindViewHolder(BaseAdapter.java:172)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5858)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5094)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4413)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:549)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by binarybucks** [comment]
Fixed
