### ISSUE TITLE
ConcurrentModificationException when updating events notification

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#415]
```
java.util.ConcurrentModificationException
	at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
	at org.owntracks.android.services.ServiceNotification.updateNotificationEvents(ServiceNotification.java:268)
	at org.owntracks.android.services.ServiceNotification.processMessage(ServiceNotification.java:356)
	at org.owntracks.android.services.ServiceMessage.processIncomingMessage(ServiceMessage.java:269)
	at org.owntracks.android.messages.MessageTransition.processIncomingMessage(MessageTransition.java:121)
	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by binarybucks** [comment]
Fixed, Notifications have been changed
