### ISSUE TITLE
Owntracks has stopped

### ISSUE THREAD

**Issue by MeiRos** [owntracks/android#493]
My Owntracks worked fine few days with private mqtt. Now it stops very often and the map isn't visible at all. It's been like this for few days. There are two users. Me and the other. I can see both locations but not on the map. Owntracks version 1.2.3 (12340). Android 6.0

**Comment by binarybucks** [comment]
This is caused by a long standing bug in the Google Maps library on Android 6. 
There is nothing we can do about this besides not showing the map. 

There are some instances were the Google Maps bug is not yet caught and hence the app crashes. 
Please submit a crash report when asked so I can see the remaining crash sources.

**Comment by MeiRos** [comment]
Crash report submitted.

**Comment by binarybucks** [comment]
Trace
```
Caused by: java.lang.NullPointerException: 
  at com.google.maps.api.android.lib6.impl.cw.c(:com.google.android.gms.DynamiteModulesB:28)
  at com.google.android.gms.maps.internal.t.onTransact(:com.google.android.gms.DynamiteModulesB:25)
  at android.os.Binder.transact(Binder.java:387)
  at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onPause(Unknown Source:0)
  at com.google.android.gms.maps.MapView$zza.onPause(Unknown Source:0)
  at com.google.android.gms.dynamic.zza.onPause(Unknown Source:0)
  at com.google.android.gms.maps.MapView.onPause(Unknown Source:0)
  at org.owntracks.android.ui.map.MapActivity.onPause(MapActivity.java:237)
  at android.app.Activity.performPause(Activity.java:6383)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3394)

````

**Comment by binarybucks** [comment]
Fix is public
