### ISSUE TITLE
Check lat/lon validity on input in geofences

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#497]
```
Caused by: java.lang.IllegalArgumentException: invalid latitude: 666.6666
    at com.google.android.gms.internal.zzcfd.<init>(Unknown Source)
    at com.google.android.gms.location.Geofence$Builder.build(Unknown Source)
    at org.owntracks.android.services.BackgroundService.setupGeofences(BackgroundService.java:531)
```

**Comment by binarybucks** [comment]
Done
