### ISSUE TITLE
App crashes when symmetric encryption is used

### ISSUE THREAD

**Issue by ardevd** [owntracks/android#533]
After enabling symmetric encryption the app now crashes every time I submit an update. 

```
03-08 13:42:32.057  8516  8516 V ServiceProxy: deliverIntentToService getServiceForIntent:org.owntracks.android.services.ServiceLocator@f9d34d2
03-08 13:42:32.061  8516  8516 V ServiceMessage: onMessageQueued()- messageId:1520512952060, queueLength:1
03-08 13:42:32.071  8516  8603 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
03-08 13:42:32.071  8516  8603 E AndroidRuntime: Process: org.owntracks.android, PID: 8516
03-08 13:42:32.071  8516  8603 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.owntracks.android-1/lib/x86_64/libkaliumjni.so" is 32-bit instead of 64-bit
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1530)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.abstractj.kalium.NaCl.<clinit>(NaCl.java:36)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.abstractj.kalium.NaCl.sodium(NaCl.java:23)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.abstractj.kalium.crypto.Random.randomBytes(Random.java:33)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.support.EncryptionProvider.encrypt(EncryptionProvider.java:56)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.support.Parser.encrypt(Parser.java:81)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.support.Parser.toJson(Parser.java:41)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.services.ServiceMessageMqtt.publishMessage(ServiceMessageMqtt.java:246)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.services.ServiceMessageMqtt.processOutgoingMessage(ServiceMessageMqtt.java:128)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:157)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at org.owntracks.android.messages.MessageBase.run(MessageBase.java:124)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-08 13:42:32.071  8516  8603 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-08 13:42:32.086  2499  3995 W ActivityManager:   Force finishing activity org.owntracks.android/.ui.map.MapActivity

```

**Comment by growse** [comment]
What device are you using?

**Comment by ardevd** [comment]
@growse I've only tried this on the emulator for now. Will see if I can reproduce it on my Pixel 2 XL as well.

**Comment by growse** [comment]
Yes please - I've seen this before on the emulator when looking at testing the symmetric encryption. It should definitely be fixed, but if it's not reproducible on a real device, it might be slightly lower priority for the moment.

**Comment by binarybucks** [comment]
We should compile the native libkalium library for 64 bit. I think some devices are dropping support for 32 bit libs. @jpmens had a docker file for it ages ago.

**Comment by jpmens** [comment]
That seems to have disappeared, sorry. (BTW, I think it was actually you who found the Dockerfile; I did build it b/c I was learning Docker at the time though. :-)

**Comment by binarybucks** [comment]
Fixed by @growse with new kalium library
