### ISSUE TITLE
"Exit app" appears to leave some reconnect logic still armed

### ISSUE THREAD

**Issue by nwf** [owntracks/android#899]
While suffering from #896, if I put OwnTracks into Manual monitoring mode and exit, it will close the foreground service, but, after a minute or so, will respawn it to let me know that it still can't validate its connection to the server.  The only way to make the foreground service stay gone is to force stop the application.

Logcat, after application exit, says
```
12-27 19:03:35.360 14289 14316 V org.owntracks.android.support.SocketFactory@b960b1f: initializing CustomSocketFactory
12-27 19:03:35.361 14289 14316 V org.owntracks.android.support.SocketFactory@b960b1f: options.hasCaCrt(): true
12-27 19:03:35.380 14289 14316 V org.owntracks.android.support.SocketFactory@b960b1f: Client .p12 sideload: false, using null client cert
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: org.owntracks.android.services.MqttConnectionException: MqttException (0) - javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(MessageProcessorEndpointMqtt.java:264)
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(MessageProcessorEndpointMqtt.java:460)
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(MessageProcessorEndpointMqtt.java:453)
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1$MessageProcessorEndpointMqtt(Unknown Source:0)
12-27 19:03:35.773 14289 14316 E MessageProcessorEndpointMqtt: 	at org.owntracks.android.services.-$$Lambda$MessageProcessorEndpointMqtt$3UR4gQL2b_UbF_ekJLIMhafolpU.run(Unknown Source:4)
12-27 19:03:35.777 14289 14309 I WM-WorkerWrapper: Worker result RETRY for Work [ id=a1d823b4-c419-4d25-a364-a74de632e00d, tags={ org.owntracks.android.services.worker.MQTTReconnectWorker, PERIODIC_TASK_MQTT_RECONNECT } ]
```

* **App build number**: 2.2.1 (22126)
* **Android version**: 10 (`lineage_h990-userdebug 10 QQ3A.200805.001 791794f2bf`)   
* **Device**: LG V20 h990ds

**Comment by growse** [comment]
Should be fixed in the next release (2.2.2).
